# Generated by Django 5.0.4 on 2024-09-27 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tematica', models.CharField(choices=[('FANTASIA', 'Fantasía'), ('CIENCIA_FICCION', 'Ciencia Ficción')], max_length=20)),
                ('descripcion', models.CharField(max_length=450)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MesaHasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('GAMEMASTER', 'Gamemaster'), ('JUGADOR', 'Jugador')], max_length=10)),
                ('fecha_rol', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roll.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mesa', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('altura', models.FloatField()),
                ('apodo', models.CharField(blank=True, max_length=45, null=True)),
                ('nivel', models.IntegerField()),
                ('hp_base', models.IntegerField()),
                ('hp_actuales', models.IntegerField()),
                ('bloqueo', models.IntegerField()),
                ('esquivar', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roll.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roll.mesahasusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('nivel', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roll.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('bonificador', models.IntegerField()),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roll.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('p_base', models.IntegerField()),
                ('bonificador', models.IntegerField()),
                ('bon_competencia', models.IntegerField()),
                ('bon_equipo', models.IntegerField()),
                ('suma_dado', models.IntegerField()),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roll.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='PjConocido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('historia', models.CharField(max_length=250)),
                ('afinidad', models.CharField(max_length=45)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roll.personaje')),
            ],
        ),
    ]
