# Generated by Django 5.0.4 on 2024-11-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='altura',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='ataque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='bloqueo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='edad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='esquivar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='hp_actuales',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='hp_base',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='personaje',
            unique_together={('mesa', 'usuario')},
        ),
    ]
